# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6e34885451c2e59f704879d9bbebc37d59b1e977017f8d3af4284064060f1763427a7ec0e72da634d99a8df38950ea05e43e721474f5516c5de4b3d4d80131a6

test:
  secret_key_base: 2c2c7f3b08a0e74dd67e69c5352c8dd44d779d18a7bdae338eb6838a7afda27bb738c2a8f503fff4b0ca5e5273cd548d6dcb1a0793fa7ae584e718abd4903476

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
